apiVersion: apps/v1
kind: Deployment
metadata:
  name: kesompochy-space-deploy
  labels:
    app: kesompochy-space
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kesompochy-space
  template:
    metadata:
      labels:
        app: kesompochy-space
    spec:
      containers:
        - name: kesompochy-space
          image: containers.kesompochy.space/kesompochy-space-app:v1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: containers-kesompochy-space-credentials

---
apiVersion: v1
kind: Service
metadata:
  name: kesompochy-space-svc
spec:
  selector:
    app: kesompochy-space
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kesompochy-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "kesompochy-clusterissuer"
spec:
  tls:
    - hosts:
        - kesompochy.space
      secretName: tls
  ingressClassName: nginx
  rules:
    - host: kesompochy.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kesompochy-space-svc
                port:
                  number: 80

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kesompochy-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kesompochy@gmail.com
    privateKeySecretRef:
      name: tls
    solvers:
      - http01:
          ingress:
            class: nginx
