apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: kesompochy-space
          image: containers.kesompochy.space/kesompochy-space-app:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 120
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      imagePullSecrets:
        - name: containers-kesompochy-space-credentials
      volumes:
        - name: html
          configMap:
            name: nginx-configmap

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
        <title>Welcome to kesompochy-space!</title>
        <meta charset="UTF-8">
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1200773173710092"
         crossorigin="anonymous"></script>
      </head>
      <body>
        <h1>ふわふわのアザラシ</h1>
      </body>
    </html>

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kesompochy-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "kesompochy-clusterissuer"
spec:
  tls:
    - hosts:
        - kesompochy.space
      secretName: tls
  ingressClassName: nginx
  rules:
    - host: kesompochy.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kesompochy-clusterissuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kesompochy@gmail.com
    privateKeySecretRef:
      name: tls
    solvers:
      - http01:
          ingress:
            class: nginx
