apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-registry
  template:
    metadata:
      labels:
        app: private-registry
    spec:
      initContainers:
        - name: prepare-htpasswd
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            [
              "mkdir -p /auth && cp /tmp/auth/htpasswd /auth/htpasswd && chown 1001:1001 /auth/htpasswd && chmod 666 /auth/htpasswd",
            ]
          volumeMounts:
            - name: auth
              mountPath: /auth
            - name: tmp-auth
              mountPath: /tmp/auth
      containers:
        - name: private-registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
          volumeMounts:
            - name: auth
              mountPath: /auth
      volumes:
        - name: auth
          emptyDir: {}
        - name: tmp-auth
          secret:
            secretName: registry-auth-secret

---
apiVersion: v1
kind: Service
metadata:
  name: private-registry
spec:
  selector:
    app: private-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
