apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kesompochy-space
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kesompochy/kesompochy-space
    targetRevision: HEAD
    path: manifests/kesompochy-space
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
