apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kesompochy-space
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/image-list: kesompochy-space-app=containers.kesompochy.space/kesompochy-space-app:latest
    argocd-image-updater.argoproj.io/my-image.update-strategy: latest
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kesompochy/kesompochy-space
    targetRevision: release
    path: manifests/kesompochy-space
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
