apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kesompochy-space
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kesompochy/kesompochy-space
    targetRevision: release
    path: manifests/kesompochy-space
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      allowEmpty: true # 追加
      imageUpdaters: # 追加
        - containerNames: ["kesompochy-space"] # 対象となるコンテナの名前を指定
          autoUpdate:
            schedule: "* * * * *" # 自動更新のスケジュールを指定