apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-registry
  labels:
    app: private-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-registry
  template:
    metadata:
      labels:
        app: private-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/auth/htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
          volumeMounts:
            - name: auth
              mountPath: /auth
              readOnly: false
      volumes:
        - name: auth
          secret:
            secretName: registry-auth-secret

---
apiVersion: v1
kind: Service
metadata:
  name: private-registry
spec:
  selector:
    app: private-registry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: private-registry
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "containers-letsencrypt"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - containers.kesompochy.space
      secretName: containers-kesompochy-tls
  rules:
    - host: containers.kesompochy.space
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: private-registry
                port:
                  number: 80

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: containers-letsencrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kesompochy@gmail.com
    privateKeySecretRef:
      name: containers-kesompochy-tls
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
