repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: nginx-ingress
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: 4.6.0
    values:
      - controller:
          config:
            ssl-port: "30443"
            client_max_body_size: "1000m"
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
