name: Release

on:
  push:
    branches:
      - main
    paths:
      - "manifests/**"
      - "!manifests/helmfiles/**"
  workflow_run:
    workflows: ["Build-and-Push", "Dump-Helmfile-Template"]
    types:
      - completed

jobs:
  release:
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Merge temp branches
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git fetch origin temp-build:temp-build || echo "temp-build branch not found"
          git fetch origin temp-dump:temp-dump || echo "temp-dump branch not found"
          git fetch origin release:release
          git switch release
          if git rev-parse --verify temp-build; then
            git merge --no-ff --allow-unrelated-histories temp-build -m "Merge build changes"
            git push origin --delete temp-build || echo "temp-build branch not found"
          fi
          if git rev-parse --verify temp-dump; then
            git merge --no-ff --allow-unrelated-histories temp-dump -m "Merge dump changes"
            git push origin --delete temp-dump || echo "temp-dump branch not found"
          fi
          git merge main --no-ff -m "Release changes"
          git push origin release
